-- V2: originally seeded demo data (admin/operator users, the "Jangirovs" sample restaurant and its
-- business hours). Deliberately emptied for production: deployments always start from a clean, empty
-- database, and no fake/demo rows may ship. The file itself must remain (never renumber or delete a
-- migration) so the version chain stays intact.
--
-- The platform operator account is no longer seeded here. It is created at first boot by
-- AdminBootstrapInitializer from the ADMIN_EMAIL / ADMIN_PASSWORD environment variables, only when
-- the users table is empty (see docs/LAUNCH.md).
--
-- Later migrations that referenced these seed rows (V31 delete of business hours, V51 restaurant
-- backfill, V128 rebrand, V147 SUPER_ADMIN promotion) are pure UPDATE/DELETE statements and no-op
-- harmlessly on an empty database.
