-- V78: originally inserted a TAKEAWAY QR code for the seeded demo restaurant (id 1). Deliberately
-- emptied for production: the demo restaurant is no longer seeded (see V2), so this INSERT would
-- violate the qr_codes.restaurant_id foreign key on a clean database. QR codes are created per
-- restaurant through the admin UI. The file remains as a no-op to keep the version chain intact.
